config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :quizzes do 
      resources :questions, only: :create
    end

    resources :questions do
      resources :options, only: :create
    end
  end

  resources :quizzes, only: [:index, :show] do
    post :submit, on: :member
  end

  get 'quiz_result/:id', to: 'quizzes#result', as: :result_quiz
  root "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :attempt
  belongs_to :question
  belongs_to :option, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :quiz
  has_many :answers, dependent: :destroy
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question

  validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many  :options, dependent: :destroy

  enum :question_type, { mcq: 0, boolean: 1, text: 2 }
  validates :content, presence: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :attempts, dependent: :destroy
end

app/controllers/admin/options_controller.rb
class Admin::OptionsController < ApplicationController

  def create
    question = Question.find(params[:question_id])
    question.options.create(option_params)
    redirect_to fallback_location: edit_admin_quiz_path(question.quiz)
  end

  private

  def option_params
    params.require(:option).permit(:content, :correct)
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def create
    quiz = Quiz.find(params[:quiz_id])
    question = quiz.questions.create!(question_params)

    # ONLY boolean questions auto-create options
    if question.boolean?
      correct_value = params[:correct_boolean]
      raise "Correct answer required" if correct_value.blank?

      question.options.create!([
        { content: "true",  correct: correct_value == "true" },
        { content: "false", correct: correct_value == "false" }
      ])
    end

    redirect_to edit_admin_quiz_path(quiz)
  end

  private

  def question_params
    params.require(:question).permit(:content, :question_type)
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController

  def index
    @quizzes = Quiz.all
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.create(quiz_params)
    redirect_to edit_admin_quiz_path(@quiz)
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  private

  def quiz_params
    params.require(:quiz).permit(:title, :published)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
  end

  def create
    admin = Admin.find_by(email: params[:email])
    if admin.present?
      if admin.authenticate(params[:password])
        session[:admin_id] = admin.id
        redirect_to admin_quizzes_path
      else
        flash[:alert] = "Invalid credentials"
        render :new
      end
    else
      flash[:alert] = "Account not exist!"
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to admin_login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  
  def index
    @quizzes = Quiz.where(published: true)
  end
  
  def show
    @quiz = Quiz.find(params[:id])
  end 

  def submit
  quiz = Quiz.find(params[:id])
  attempt = quiz.attempts.create!(score: 0)

  score = 0

  # MCQ answers
  if params[:answers]
    params[:answers].each do |question_id, option_id|
      option = Option.find(option_id)
      attempt.answers.create!(
        question_id: question_id,
        option_id: option_id
      )
      score += 1 if option.correct?
    end
  end

  # Text answers (no auto scoring)
  if params[:text_answers]
    params[:text_answers].each do |question_id, text|
      attempt.answers.create!(
        question_id: question_id,
        text_answer: text
      )
    end
  end

  # Boolean answers (optional scoring)
  if params[:boolean_answers]
    params[:boolean_answers].each do |question_id, value|
      correct_option = Option.find_by(
        question_id: question_id,
        correct: true
      )

      attempt.answers.create!(
        question_id: question_id,
        text_answer: value
      )

      score += 1 if correct_option&.content == value
    end
  end

  attempt.update!(score: score)
  redirect_to result_quiz_path(attempt)
end


  def result
    @attempt = Attempt.find(params[:id])
  end
end

app/helpers/admin/options_helper.rb
module Admin::OptionsHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/admin/questions/edit.html.erb
<!-- app/views/admin/quizzes/edit.html.erb -->
<h2><%= @quiz.title %></h2>

<h3>Add Question</h3>

<%= form_with url: admin_quiz_questions_path(@quiz) do %>
  <input name="question[content]" placeholder="Question text">
  <select name="question[question_type]">
    <option value="mcq">MCQ</option>
    <option value="boolean">True / False</option>
    <option value="text">Text</option>
  </select>
  <button>Add</button>
<% end %>

<hr>

<h3>Questions</h3>
<% @quiz.questions.each do |q| %>
  <p><strong><%= q.content %></strong></p>

  <% if q.mcq? || q.boolean? %>
    <%= form_with url: admin_question_options_path(q) do %>
      <input name="option[content]" placeholder="Option text">
      <label>
        <input type="checkbox" name="option[correct]">
        Correct
      </label>
      <button>Add Option</button>
    <% end %>
  <% end %>

  <ul>
    <% q.options.each do |o| %>
      <li>
        <%= o.content %>
        <% if o.correct %>✔<% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/quizzes/edit.html.erb
<a href="/"> GO Home</a>
<h2><%= @quiz.title %></h2>

<h3>Add Question</h3>

<%= form_with url: admin_quiz_questions_path(@quiz), local: true do %>
  <input type="text" name="question[content]" placeholder="Question text" required>

  <select name="question[question_type]" id="question_type">
    <option value="mcq">MCQ</option>
    <option value="boolean">True / False</option>
    <option value="text">Text</option>
  </select>

  <div id="boolean_correct" style="display:none">
    <label>
      <input type="radio" name="correct_boolean" value="true"> True
    </label>
    <label>
      <input type="radio" name="correct_boolean" value="false"> False
    </label>
  </div>

  <button type="submit">Add Question</button>
<% end %>

<hr>

<h3>Questions</h3>

<% @quiz.questions.each do |q| %>
  <p>
    <strong>Question: <%= q.content %></strong>
    (<%= q.question_type %>)
  </p>

  <% if q.mcq? %>
    <%= form_with url: admin_question_options_path(q), local: true do %>
      <input type="text"
             name="option[content]"
             placeholder="Option text"
             required>

      <label>
        <input type="checkbox" name="option[correct]">
        Correct
      </label>

      <button type="submit">Add Option</button>
    <% end %>
  <% end %>

  <% if q.options.any? %>
    <ul>
      <% q.options.each do |o| %>
        <li>
          <%= o.content %>
          <% if o.correct %>✔<% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<script>
  document.getElementById("question_type").addEventListener("change", function () {
    document.getElementById("boolean_correct").style.display =
      this.value === "boolean" ? "block" : "none";
  });
</script>

app/views/admin/quizzes/index.html.erb
<h1>List of Quizzes</h1>
<a href="<%= new_admin_quiz_path %>" >New Quiz</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Published</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.title %></td>

        <td>
          <% if quiz.published %>
            <span class="badge badge-success">Yes</span>
          <% else %>
            <span class="badge badge-secondary">No</span>
          <% end %>
        </td>

        <td>
          <%= link_to 'Edit', edit_admin_quiz_path(quiz), class: 'btn btn-sm btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/quizzes/new.html.erb
<h1>New Quiz</h1>
<%= form_with model: [:admin, @quiz], local: true do |f| %>
  <%= f.label :title, "Quiz Title" %><br>
  <%= f.text_field :title, required: true %>
  <div><br>
    <%= f.label :published, "Publish Quiz?" %><br>
    <%= f.check_box :published %>
  </div><br>
    <%= f.submit 'Create Quiz' %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Quiz System</h1>

<div style="margin-top: 30px;">
  <a href="<%= admin_login_path %>">
    <button>Admin</button>
  </a>

  <a href="<%= quizzes_path %>">
    <button>User</button>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quiz System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/index.html.erb
<h2>Available Quizzes</h2>
<ul>
  <%if @quizzes.present? %>
    <% @quizzes.each do |quiz| %>
      <li>
        <a href="<%= quiz_path(quiz) %>">
          <%= quiz.title %>
        </a>
      </li>
    <% end %>
  <%else%>
    No Quiz Available
  <%end%>
</ul>

app/views/quizzes/result.html.erb
<h2>Quiz Result</h2>
<p>Your Score: <%= @attempt.score %></p>
<a href="/"> GO Home</a>

app/views/quizzes/show.html.erb
<h1><%= @quiz.title %></h1>

<%= form_with url: submit_quiz_path(@quiz),
              method: :post,
              local: true do %>

  <% @quiz.questions.each do |q| %>
    <p><strong>Question: <%= q.content %></strong></p>

    <% if q.mcq? || q.boolean? %>
      <% q.options.each do |o| %>
        <label>
          <input type="radio"
                 name="answers[<%= q.id %>]"
                 value="<%= o.id %>">
          <%= o.content.capitalize %>
        </label><br>
      <% end %>

    <% elsif q.text? %>
      <input type="text"
             name="text_answers[<%= q.id %>]"
             placeholder="Your answer">
    <% end %>

  <% end %>

  <br><br>
  <button type="submit">Submit Quiz</button>
<% end %>